require Pod::Executable.execute_command('node', ['-e',
  'process.stdout.write(require(\'react-native/package.json\').version)', '--']).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Enabling #{linkage}ly linked Frameworks (use_frameworks! :linkage => #{linkage.to_sym})"
  use_frameworks! :linkage => linkage.to_sym
end

target 'FaceGuardOffline' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # react-native-fast-tflite: needs TensorFlowLiteC
  pod 'TensorFlowLiteC', '~> 2.14.0'
  pod 'TensorFlowLiteSelectTfOps', '~> 2.14.0'

  target 'FaceGuardOfflineTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        # Enable Metal for GPU inference
        config.build_settings['MTL_FAST_MATH'] = 'YES'
      end
    end
  end
end
